version: "3.8"
services: 
    bookstore:
      build: 
        context: .
      ports: 
        - "8083:8080"
      container_name: bookStoreV.1
    postgres:
      image: postgres:13.1
      healthcheck:
        test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
        timeout: 45s
        interval: 10s
        retries: 10
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=boat
        - APP_DB_USER=docker
        - APP_DB_PASS=docker
        - APP_DB_NAME=docker
      volumes:
      - ./db:/docker-entrypoint-initdb.d/
      ports:
        - 5434:5432